GET https://v1.nocodeapi.com/amutha/google_sheets/sDBpXXCxMheMRxIY?tabId=Sheet2

# POST https://v1.nocodeapi.com/amutha/google_sheets/sDBpXXCxMheMRxIY?tabId=Sheet1
# content-type: application/json

# {
# "Name" : 4, "Email": "tamamutha@gmail.com", Message: "hi testing", "time": "Wed, 21 Oct 2015 18:27:50 GMT",
# }